import type { App } from 'vue'
import {
    Apple,
    ArrowDown,
    ArrowRight,
    Avatar,
    Box,
    Check,
    Cherry,
    Close,
    Collection,
    CopyDocument,
    Cpu,
    CreditCard,
    Delete,
    Document,
    Edit,
    Finished,
    Folder,
    Food,
    FullScreen,
    InfoFilled,
    Key,
    MagicStick,
    Minus,
    Monitor,
    Notebook,
    Picture,
    PieChart,
    Plus,
    PriceTag,
    Refresh,
    RefreshLeft,
    Search,
    Setting,
    Star,
    SuccessFilled,
    SwitchButton,
    Tickets,
    Tools,
    Upload,
    User,
    UserFilled,
    Watch,
} from '@element-plus/icons-vue'

/**
 * 注册 ElButton icon="Xxx" / <component :is="icon"/> 会用到的图标。
 * 同时注册小写别名，兼容历史写法 icon="edit"。
 */
const icons: Record<string, object> = {
    Apple,
    ArrowDown,
    ArrowRight,
    Avatar,
    Box,
    Check,
    Cherry,
    Close,
    Collection,
    CopyDocument,
    Cpu,
    CreditCard,
    Delete,
    Document,
    Edit,
    Finished,
    Folder,
    Food,
    FullScreen,
    InfoFilled,
    Key,
    MagicStick,
    Minus,
    Monitor,
    Notebook,
    Picture,
    PieChart,
    Plus,
    PriceTag,
    Refresh,
    RefreshLeft,
    Search,
    Setting,
    Star,
    SuccessFilled,
    SwitchButton,
    Tickets,
    Tools,
    Upload,
    User,
    UserFilled,
    Watch,
}

// 小写 / kebab 别名（模板里混用了 edit、delete、check、close、price-tag 等）
const aliases: Record<string, object> = {
    check: Check,
    close: Close,
    delete: Delete,
    edit: Edit,
    finished: Finished,
    plus: Plus,
    refresh: Refresh,
    search: Search,
    tickets: Tickets,
    upload: Upload,
    user: User,
    'price-tag': PriceTag,
    'copy-document': CopyDocument,
    'magic-stick': MagicStick,
    'refresh-left': RefreshLeft,
}

export function registerIcons(app: App) {
    for (const [name, component] of Object.entries({...icons, ...aliases})) {
        app.component(name, component)
    }
}
