import type { App } from 'vue'
import {
    Apple,
    ArrowDown,
    Avatar,
    Box,
    Check,
    Cherry,
    Close,
    Collection,
    Cpu,
    CreditCard,
    Delete,
    Document,
    Finished,
    Folder,
    Food,
    FullScreen,
    InfoFilled,
    Key,
    Minus,
    Monitor,
    Notebook,
    Picture,
    PieChart,
    PriceTag,
    Setting,
    Star,
    SuccessFilled,
    SwitchButton,
    Tickets,
    Tools,
    Upload,
    User,
    UserFilled,
    Watch,
} from '@element-plus/icons-vue'

/** 只注册实际用到的图标，避免打包全部 @element-plus/icons-vue */
const icons = {
    Apple,
    ArrowDown,
    Avatar,
    Box,
    Check,
    Cherry,
    Close,
    Collection,
    Cpu,
    CreditCard,
    Delete,
    Document,
    Finished,
    Folder,
    Food,
    FullScreen,
    InfoFilled,
    Key,
    Minus,
    Monitor,
    Notebook,
    Picture,
    PieChart,
    PriceTag,
    Setting,
    Star,
    SuccessFilled,
    SwitchButton,
    Tickets,
    Tools,
    Upload,
    User,
    UserFilled,
    Watch,
    // StatisticMain 里有小写 / kebab 别名
    user: User,
    tickets: Tickets,
    finished: Finished,
    'price-tag': PriceTag,
}

export function registerIcons(app: App) {
    for (const [name, component] of Object.entries(icons)) {
        app.component(name, component)
    }
}
